# Tensors

张量是一种专门的数据结构，与数组和矩阵非常相似。 在 PyTorch 中，我们使用张量来编码模型的输入和输出，以及模型的参数。 张量类似于 [NumPy](https://numpy.org/) 的`ndarrays`，但张量可以在 GPU 或其他硬件加速器上运行。 事实上，Tensors 和 NumPy 数组通常可以共享相同的底层内存，无需复制数据（请参阅与 [NumPy 的桥接](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）。 张量还针对自动微分进行了优化（稍后我们将在 [Autograd](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html) 部分了解更多相关信息）。 如果你熟悉`ndarrays`，那么使用张量 API 就会得心应手。 如果不熟悉，请继续学习！

In [1]:
import torch
import numpy as np

## 初始化张量

张量可以通过多种方式初始化。

### 直接从数据初始化

张量可以直接从数据创建。数据类型会自动推断。

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

### 从 Numpy 数组初始化

可以从 NumPy 数组创建张量（反之亦然 - 参见使用 [NumPy 的桥接](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）。

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### 从其他 Tensor 初始化

除非明确覆盖，否则新的张量将保留参数张量的属性（形状、数据类型）。

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor:
 tensor([[0.6614, 0.0480],
        [0.0949, 0.8235]]) 



### 随机或常量值

`shape` 是张量维度的元组。在下面的函数中，它决定了输出张量的维数。

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n {rand_tensor} \n")
print(f"One Tensor: \n {ones_tensor} \n")
print(f"Zero Tensor: \n {zeros_tensor} \n")

Random Tensor:
 tensor([[0.0884, 0.2094, 0.1110],
        [0.7800, 0.4359, 0.5054]]) 

One Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 张量的属性

张量属性描述它们的形状、数据类型和存储它们的设备。

In [6]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 张量操作

这里全面描述了 100 多个张量运算，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等。

这些操作中的每一个都可以在 GPU 上运行（通常比在 CPU 上运行的速度更快）。如果您使用 Colab，请转到运行时 > 更改运行时类型 > GPU 来分配 GPU。

默认情况下，张量是在 CPU 上创建的。我们需要使用 `.to` 方法明确将张量移动到 GPU（在检查 GPU 可用性之后）。请记住，跨设备复制大型张量在时间和内存方面可能会很昂贵！

In [7]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

[ROCT-Thunk-Interface/src/hymgr.c:309, WARNING]: Version mismatch


尝试列表中的某些操作。如果您熟悉 NumPy API，您会发现 Tensor API 非常容易使用。

### 标准 numpy 样式索引和切片

In [8]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last colum: {tensor[..., -1]}")
tensor[:, 1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last colum: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 连接张量

您可以使用 `torch.cat` 沿给定维度连接一系列张量。另请参阅 `torch.stack`，这是另一个与 `torch.cat` 略有不同的张量连接运算符。

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
shape1 = (2, 3, 4)
shape2 = (2, 4, 4)
tensor1 = torch.rand(shape1)
tensor2 = torch.rand(shape2)
tensor_cat = torch.cat([tensor1, tensor2], dim=1)
print(tensor1)
print(tensor2)
print(tensor_cat)

tensor([[[0.0170, 0.5718, 0.9582, 0.1413],
         [0.8573, 0.4393, 0.4413, 0.6593],
         [0.8606, 0.9637, 0.3154, 0.1142]],

        [[0.6672, 0.6707, 0.7186, 0.6208],
         [0.1382, 0.1943, 0.4156, 0.5072],
         [0.6009, 0.0522, 0.6470, 0.2042]]])
tensor([[[0.5100, 0.9052, 0.2818, 0.4196],
         [0.9464, 0.2380, 0.3300, 0.1148],
         [0.9690, 0.0277, 0.4810, 0.9035],
         [0.4706, 0.4664, 0.4136, 0.6139]],

        [[0.6039, 0.0271, 0.0154, 0.6438],
         [0.5457, 0.0680, 0.8596, 0.7881],
         [0.4078, 0.7854, 0.2423, 0.4749],
         [0.9580, 0.5843, 0.9059, 0.4782]]])
tensor([[[0.0170, 0.5718, 0.9582, 0.1413],
         [0.8573, 0.4393, 0.4413, 0.6593],
         [0.8606, 0.9637, 0.3154, 0.1142],
         [0.5100, 0.9052, 0.2818, 0.4196],
         [0.9464, 0.2380, 0.3300, 0.1148],
         [0.9690, 0.0277, 0.4810, 0.9035],
         [0.4706, 0.4664, 0.4136, 0.6139]],

        [[0.6672, 0.6707, 0.7186, 0.6208],
         [0.1382, 0.1943, 0.4156, 0.5072],
 

### 算术操作

In [24]:
# 计算矩阵乘，也就是 y1,y2,y3 拥有相同的值
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(f"Matmul: {y1}")

# 逐元素乘积，z1,z2,z3有相同值
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"Mul: {z1}")

Matmul: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
Mul: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 单元素张量

如果你有一个单元素张量，例如通过将张量的所有值聚合为一个值，则可以使用 `item()` 将其转换为 Python 数值：

In [25]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### 就地运算(In-place Operations)

将结果存储到操作数中的运算称为就地运算。它们以 `_` 后缀表示。例如：`x.copy_(y)`、`x.t_()`，将更改 `x`。

In [26]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


> 就地操作可以节省一些内存，但在计算导数时可能会出现问题，因为会立即丢失历史记录。因此，不鼓励使用它们。

## 与 numpy 桥接

CPU 和 NumPy 数组上的张量可以共享其底层内存位置，改变其中一个也会改变另一个。

### Tensor 转为 numpy 数组

In [27]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


张量的变化反映在 NumPy 数组中。

In [28]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### Numpy 数组转为 Tensor

In [29]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


numpy 数组的变化反映在张量中。

In [30]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
